import type { FormStructure } from "@/interfaces/form";
import type { FormDataSchema } from "../schemas/form";

export const formStructure: FormStructure<FormDataSchema>[] = [
  {
    sectionTitle: "Datos del solicitante",
    fields: [
      {
        field: "fecha_solicitud",
        label: "Fecha solicitud requerimientos logísticos",
        type: "date",
        isRequired: true,
      },
      {
        field: "subdireccion",
        label: "Subdirección que solicita",
        type: "select",
        isRequired: true,
        options: [
          "Subdirección de Gestión, Redes Sociales e Informalidad (SGRSI)",
          "Subdirección de Emprendimiento, Servicios Empresariales y Comercialización (SESEC)",
        ],
      },
    ],
  },
  {
    sectionTitle: "Datos del evento",
    fields: [
      {
        field: "lugar_del_evento",
        label: "Lugar del evento requerimientos logísticos",
        type: "select",
        isRequired: true,
        options: [
          "20 de Julio",
          "Alameda Vicacha",
          "Bodega la 38",
          "Bodega Usme",
          "Box Coulvert",
          "Centenario",
          "Estación Las Flóres",
          "Furatena",
          "Manzana 22",
          "Parque Olaya",
          "Plaza 7 de Agosto",
          "Plaza de Bolivar",
          "Plaza España",
          "Plaza Fontibón",
          "Plaza La Concordia",
          "Plaza Murillo Toro",
          "Plaza Samper Mendoza",
          "Plazoleta El Rosario",
          "Portal Suba",
          "Quirigua",
          "Rotonda Chapinero",
          "Santa Fe",
          "Santa Lucia",
          "Veracruz",
          "Otros",
        ],
      },
      {
        field: "fecha_inicio_evento",
        label: "Fecha y hora inicio del evento",
        type: "datetime",
        isRequired: true,
      },
      {
        field: "fecha_finalizacion_evento",
        label: "Fecha y hora finalización del evento",
        type: "datetime",
        isRequired: true,
      },
      {
        field: "requerimientos_audio_video",
        label: "Requerimientos de audio y video",
        type: "multi_select_and_amount",
        isRequired: true,
        options: [
          "Alquiler de sonido de 50 a 150 pax",
          "Alquiler de sonido de 200 a 500 pax",
          "Backline",
          "Micrófono inalámbrico",
          "Pantalla Led 3X2",
          "Pantalla Led 4X3",
          "Ninguno",
          "Otros",
        ],
      },
      {
        field: "requerimientos_catering",
        label: "Requerimientos de catering",
        type: "multi_select_and_amount",
        isRequired: true,
        options: [
          "Agua en botella",
          "Almuerzo o cena",
          "Desayuno",
          "Lechona",
          "Refrigerio de dulce",
          "Refrigerio de sal",
          "Ninguno",
          "Otros",
        ],
      },
      {
        field: "xxxxxx",
        label: "Por definir",
        type: "multi_select_and_amount",
        isRequired: true,
        options: [
          "Banderines - 10 Metros de Banderines Triangulares o Festones",
          "Backing 4X2",
          "Backing 6X2",
          "Sistema de iluminación",
          "Tarima 5X2",
          "Tarima 3X2",
          "Tarima 6X3",
          "Ninguno",
          "Otros",
        ],
      },
      {
        field: "requerimientos_espacios",
        label: "Requerimientos de espacios para eventos",
        type: "select",
        isRequired: true,
        options: [
          "Salón / Auditorio 150 personas",
          "Salón / Auditorio 500 personas",
          "Ninguno",
          "Otros",
        ],
      },
      {
        field: "requerimientos_estructuras_exteriores",
        label: "Requerimientos de estructuras exteriores",
        type: "multi_select_and_amount",
        isRequired: true,
        options: [
          "Baño portátil",
          "Carpa 2x2",
          "Carpa 3x3",
          "Carpa 4x4",
          "Carpa 6x6",
          "Carpa 12x6",
          "Valla de contención y cerramiento",
          "Ninguno",
          "Otros",
        ],
      },
      {
        field: "requerimientos_publicidad",
        label: "Requerimientos materiales publicitarios",
        type: "multi_select_and_amount",
        isRequired: true,
        options: [
          "Pendón 1 - Banner 1.50 x 1.00 m",
          "Pendón 2 - Banner con estructura de araña 2.00 x 1.00 m",
          "Pendón 3 - Banner 2.50 x 1.50 m",
          "Pendón 4 - Banner 3.00 x 1.80 m",
          "Pendón 5 - Banner 3.50 x 1.50 m",
          "Ninguno",
          "Otros",
        ],
      },
      {
        field: "requerimientos_mobiliario",
        label: "Requerimientos de mobiliario",
        type: "multi_select_and_amount",
        isRequired: true,
        options: [
          "Alquiler silla",
          "Alquiler de mesa cuadrada",
          "Alquiler de mesa tipo tablón",
          "Alquiler mesa rectangular",
          "Alquiler mesa redonda",
          "Ninguno",
          "Otros",
        ],
      },
      {
        field: "requerimientos_personal",
        label: "Requerimientos de personal de apoyo",
        type: "multi_select_and_amount",
        isRequired: true,
        options: [
          "Animador y/o presentador con experiencia",
          "Auxiliar Logístico apoyo eventos",
          "Auxiliar Logístico montaje y desmontaje mobiliario",
          "Brigadista",
          "Enfermero",
          "Grupo musical",
          "Mesero",
          "Seguridad",
          "Ninguno",
          "Otros",
        ],
      },
      {
        field: "requerimientos_servicios_audiovisuales",
        label: "Requerimientos de servicios audiovisuales",
        type: "multi_select_and_amount",
        isRequired: true,
        options: [
          "Circuito cerrado de televisión",
          "Streaming HD",
          "Streaming Full HD",
          "Ninguno",
          "Otros",
        ],
      },
      {
        field: "requerimientos_servicios_salud_emergencia",
        label: "Requerimientos de servicios de salud y emergencia",
        type: "select",
        isRequired: true,
        options: [
          "Módulo estabilización y clasificación (MEC) - Baja complejidad",
          "Módulo estabilización y clasificación (MEC) - Alta complejidad",
          "Ninguno",
          "Otros",
        ],
      },
      {
        field: "requerimientos_suministro_energia",
        label: "Requerimientos de suministro de energía",
        type: "multi_select_and_amount",
        isRequired: true,
        options: [
          "Planta eléctrica - 40 KVA",
          "Planta eléctrica - 50 KVA",
          "Planta eléctrica - 75 KVA",
          "Planta eléctrica - 120 KVA",
          "Planta eléctrica - 170 KVA",
          "Parcial de corriente",
          "Distribuidor de corriente",
          "Punto eléctrico en carpa",
          "Punto de luz en carpa",
          "Ninguno",
        ],
      },
      {
        field: "requerimientos_transporte",
        label: "Requerimientos de transporte",
        type: "select",
        isRequired: true,
        options: [
          "Transporte 2.5 Ton",
          "Transporte 6.5 Ton",
          "Ninguno",
          "Otros",
        ],
      },
    ],
  },
];
